import { LightningElement } from 'lwc';
import {NavigationMixin} from 'lightning/navigation';
import login from '@salesforce/apex/splitify_service.login'
import signUp from '@salesforce/apex/splitify_service.signUp'
import sendEmail from '@salesforce/apex/GmailService.sendEmail';
import forgotPasswordHandler from '@salesforce/apex/splitify_service.forgotPasswordHandler';
import duplicateEmailVerification from '@salesforce/apex/splitify_service.duplicateEmailVerification';
import addToGroup from '@salesforce/apex/splitify_service.addToGroup';

export default class LoginPage extends NavigationMixin(LightningElement) {

    showLoginErrorMessage = false;
    showSignUpErrorMessage = false;
    showSignUpErrorForEmail = false;
    showVerificationErrorMessage = false;
    showForgotPasswordErrorForEmail = false;
    showForgotPasswordErrorForCode = false;
    showNewPasswordError = false;
    isLoading = false;
    autoGeneratedCode;


    renderedCallback(){
       
    }

    handleLogin(event){
        event.preventDefault()
        this.isLoading = true;
        this.showLoginErrorMessage = false;

        const email = event.target.email.value.trim();
        const password = event.target.password.value.trim();

        login({Email: email, Password: password})
        .then((data) => {
            if(data == null || data === 'error'){
                this.isLoading = false;
                this.showLoginErrorMessage = true;
                return;
            }
            localStorage.setItem('userId', data);
            localStorage.setItem('refresh', 'true');

            this[NavigationMixin.Navigate]({

                type: 'comm__namedPage',
                attributes: {
                    name: 'Home'
                },
                state : {
                    // "userId" : "12345abcd"
                }
            })
            this.isLoading = false;
        })
        .catch(error => {
            this.isLoading = false;
            this.showLoginErrorMessage = true;

        })
        
        
    }

    handleSignUp(event){
        event.preventDefault();
        this.isLoading = true;
        this.showSignUpErrorForEmail = false;
        this.showSignUpErrorMessage = false;

        // const signupEl = this.template.querySelector('.signup');
        // const verificationEl = this.template.querySelector('.verification');

        const fullName = event.target.name.value.trim().split(' ').filter(word => word != '').join(' ');
        const email = event.target.email.value.trim();
        const password = event.target.password.value.trim();
        const confirmPassword = event.target.confirmPassword.value.trim();

        if(password !== confirmPassword){
            this.showSignUpErrorMessage = true;
            this.isLoading = false;
            return;
        }

        duplicateEmailVerification({Email: email})
        .then((data) => {
            if(data === "email exist"){
                this.showSignUpErrorForEmail = true;
                return Promise.reject('Email already exists');
            }

            signUp({Fullname: fullName, Email: email, Password: password})
            .then((data) => {

                localStorage.setItem('userId', data);
                localStorage.setItem('refresh', 'true');

                const inviteId = localStorage.getItem('inviteId');
                if(inviteId){
                    this.addToInvitedGroup(inviteId, data);
                    this.isLoading = false;
                    return;
                }

                this.navigateToHomePage();
                this.isLoading = false;
            })
            .catch(error => {
                console.error('error while signing up  :', error);
            })
            //const verificationCode  = this.generateSixDigitRandomNumber().toString();
            //return sendEmail({ toEmail: email, contentBody: verificationCode, Heading: 'Splitify' });
        })
        // .then (() => {
        //     this.transitionToVerification(signupEl,verificationEl);
        // })
        .catch((error) => {
            console.error('error', error);
        })
        .finally(() => {
            this.isLoading = false;
        })

        //sign up user creation
        
    }

    // transitionToVerification(signupEl, verificationEl) {
    //     signupEl.style.translate = '-120%';
    //     verificationEl.style.translate = '0%';
    // }

    // handleEmailVerification(event){
    //     event.preventDefault();
    //     this.isLoading = true;
    //     const signUpForm = this.template.querySelector('.sign-up-form');
    //     const verificationCode = event.target.verificationCode.value.trim();
    //     if(this.autoGeneratedCode != verificationCode){
    //         this.showVerificationErrorMessage = true;
    //         this.isLoading = false;
    //         return;
    //     }
    //     const fullName = signUpForm.name.value.trim().split(' ').filter(word => word != '').join(' ');
    //     const email = signUpForm.email.value.trim();
    //     const password = signUpForm.password.value.trim();

    //     signUp({Fullname: fullName, Email: email, Password: password})
    //     .then((data) => {

    //         localStorage.setItem('userId', data);
    //         localStorage.setItem('refresh', 'true');

    //         const inviteId = localStorage.getItem('inviteId');
    //         if(inviteId){
    //             this.addToInvitedGroup(inviteId, data);
    //             this.isLoading = false;
    //             return;
    //         }

    //         this.navigateToHomePage();
    //         this.isLoading = false;
    //     })
    //     .catch(error => {
    //         console.error('error while signing up  :', error);
    //     })
    // }

    addToInvitedGroup(groupId, userId){
        addToGroup({GroupId : groupId, UserId: userId})
        .then(() => {
            localStorage.removeItem('inviteId');
            this.navigateToHomePage();
        })
        .catch((error) => {
            this.showError = error.body.exceptionType + ' : '+ error.body.message;
            console.error('error while adding user to group : ',error);
        })
    }

    navigateToHomePage(){
        this[NavigationMixin.Navigate]({

            type: 'comm__namedPage',
            attributes: {
                name: 'Home'
            },
            state : {}
        })
    }

    showSignUpPage(){
            const signUpPage = this.template.querySelector('.signup-container');
            const loginPage = this.template.querySelector('.login-container');

            loginPage.style.height = '3.3rem';
            loginPage.style.padding = '0.5rem';
            signUpPage.style.height = '26rem';
            signUpPage.style.padding = '3rem 2rem';
            
    }

    showLoginPage(){
            const loginPage = this.template.querySelector('.login-container');
            const signUpPage = this.template.querySelector('.signup-container');

            loginPage.style.height = '22rem';
            loginPage.style.padding = '3rem 2rem';
            signUpPage.style.height = '3.3rem';
            signUpPage.style.padding = '0rem';
    }

    generateSixDigitRandomNumber() {
        this.autoGeneratedCode = Math.floor(100000 + Math.random() * 900000);
        return this.autoGeneratedCode;
    }

    handleForgotPassword(event){
        this.template.querySelector('.login').style.translate = '-120%';
        this.template.querySelector('.forgot-password-container').style.translate = '0%';
    }

    //forgot password container logic

    goBackToLoginComponent(event){
        this.template.querySelector('.login').style.translate = '0%'
        this.template.querySelector('.forgot-password-container').style.translate = '120%';
    }

    forgotPasswordEmailHandler(event){
        event.preventDefault();
        this.showForgotPasswordErrorForEmail = false;

        this.isLoading = true;
        const forgotPasswordCodeForm = this.template.querySelector('.forgot-password-code-form');
        const email = event.target.email.value.trim();
        const forgotPasswordEmailFormEl = event.currentTarget;

        forgotPasswordHandler({Email: email, Password: ''})
        .then((data) => {
            if(data === 'true'){
                this.isLoading = false;
                
                forgotPasswordEmailFormEl.style.translate = "-120%";
                forgotPasswordCodeForm.style.translate = '0%';

                const sixDigitString = this.generateSixDigitRandomNumber().toString();
                
                sendEmail({toEmail : email, contentBody : sixDigitString, Heading: 'Reset Password'})
                .then(() => {
                })
                .catch(error => {

                })
            }
        })
        .catch((error) => {
            this.showForgotPasswordErrorForEmail = true;
            this.isLoading = false;
        }) 
    }
    goBackToForgotPasswordEmail(){
        this.template.querySelector('.forgot-password-code-form').style.translate = '120%';
        this.template.querySelector('.forgot-password-email').style.translate = '0%';
    }

    forgotPasswordCodeHandler(event){
        event.preventDefault();
        this.showForgotPasswordErrorForCode = false;
        this.isLoading = true;
        const code = event.target.forgotPasswordCode.value.trim();

        if(code != this.autoGeneratedCode){
            this.showForgotPasswordErrorForCode = true;
            this.isLoading = false;
            return;
        }
        const newPasswordForm = this.template.querySelector('.new-password-form');
        this.isLoading = false;
        event.currentTarget.style.translate = "-120%";
        newPasswordForm.style.translate = '0%';
    }

    goBackToLoginComponent(){
        this.template.querySelector('.forgot-password-container').style.translate = '120%';
        this.template.querySelector('.login').style.translate = '0%';
        const newPasswordForm = this.template.querySelector('.new-password-form');
        const forgotPasswordCodeForm = this.template.querySelector('.forgot-password-code-form');
        const forgotPasswordEmailForm = this.template.querySelector('.forgot-password-email');
        forgotPasswordEmailForm.style.translate = '0%';
        newPasswordForm.style.translate = '120%';
        forgotPasswordCodeForm.style.translate = '120%';
        forgotPasswordEmailForm.reset();
        newPasswordForm.reset();
        forgotPasswordCodeForm.reset();
    }
    
    newPasswordHandler(event){
        event.preventDefault();
        this.showNewPasswordError = false;
        this.isLoading = true;
        const email = this.template.querySelector('.forgot-password-email').email.value.trim();
        const newPassword = event.target.newPassword.value.trim();
        const newConfirmPassword = event.target.newConfirmPassword.value.trim();
        if(newPassword !== newConfirmPassword){
            this.showNewPasswordError = true;
            this.isLoading = false;
            return;
        }

         forgotPasswordHandler({Email: email, Password: newPassword})
        .then((data) => {
            const toast = this.template.querySelector('c-custom-toast');
            toast.show('Password Changed! Please Login.', 'success');
            this.isLoading = false;

            localStorage.setItem('userId', data);
            this.goBackToLoginComponent();
        })
        .catch((error) => {
            const toast = this.template.querySelector('c-custom-toast');
            toast.show(error, 'error');
        })
    }
    
}